<?php



/**
 * Skeleton subclass for performing query and update operations on the 'tab_priority' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.6.3 on:
 *
 * Sat Jan 14 00:08:11 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class PriorityPeer extends BasePriorityPeer {

} // PriorityPeer
